version: '3'
services:
  api:
    build:
      context: ./api
    restart: always
    volumes:
      - ./api/app:/www/app:delegated
  web-client:
    build:
      context: ./web-client
    restart: always
  web-server:
    build:
      context: ./web-server
    restart: always
    links:
      - api
      - web-client
    ports:
      - '8080:80'